# Generated by Django 3.0.3 on 2020-03-28 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200319_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsCheckboxQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDescription', models.CharField(max_length=1000000000)),
            ],
        ),
        migrations.AddField(
            model_name='clssurvey',
            name='nLen',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='clsTextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDescription', models.CharField(max_length=1000000000)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.clsSurvey')),
            ],
        ),
        migrations.CreateModel(
            name='clsTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strAnswer', models.CharField(max_length=1000000000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.clsTextQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='clsSingleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDescription', models.CharField(max_length=1000000000)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.clsSurvey')),
            ],
        ),
        migrations.CreateModel(
            name='clsOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('strDescription', models.CharField(max_length=1000000000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.clsCheckboxQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='clscheckboxquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.clsSurvey'),
        ),
    ]
